version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: wiktor
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: POSTGRES_DB
    ports:
      - "5432:5432"
